# Generated by Django 3.0.7 on 2021-04-03 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='lectures',
            field=models.SmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='course',
            name='practicals',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='self_study',
            field=models.DecimalField(decimal_places=1, default=2, max_digits=2),
        ),
        migrations.AddField(
            model_name='course',
            name='tutorials',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_credits',
            field=models.DecimalField(decimal_places=1, default=3, max_digits=2),
        ),
    ]
