# Generated by Django 3.0.7 on 2021-04-03 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20210403_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesection',
            name='semester',
            field=models.CharField(choices=[('1', 'First'), ('2', 'Second')], max_length=1),
        ),
    ]
