# Generated by Django 3.0.7 on 2021-04-04 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='facultytakescourse',
            name='course',
        ),
        migrations.RemoveField(
            model_name='facultytakescourse',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='facultytakescourse',
            name='year',
        ),
    ]
